### ISSUE TITLE
Errors when opening Appconfig in Admin:

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/hoodie-plugin-appconfig#6]
`GET http://127.0.0.1:6005/_api/plugins/_changes?include_docs=true&since=0 401 (Unauthorized)vendor.js:5 ab.ajaxTransport.Z.cors.a.crossDomain.sendvendor.js:5 ab.extend.ajaxadmin-dashboard.js:1 badmin-dashboard.js:1 w.requestadmin-dashboard.js:1 w.pulladmin-dashboard.js:1 w.bootstrapadmin-dashboard.js:1 w.connectadmin-dashboard.js:1 cadmin-dashboard.js:1 b.extendadmin-dashboard.js:1 cadmin-dashboard.js:2 (anonymous function)admin-dashboard.js:2 42.../../../helpers/namespaceadmin-dashboard.js:1 eadmin-dashboard.js:1 (anonymous function)admin-dashboard.js:3 86../components/admin-dashboard/entities/adminEntityadmin-dashboard.js:1 eadmin-dashboard.js:1 aadmin-dashboard.js:1 (anonymous function)`

` GET http://127.0.0.1:6005/_api/_plugins/_assets/styles/admin-dashboard-uikit.css  404`
` GET http://127.0.0.1:6005/_api/_plugins/_assets/scripts/admin-dashboard-uikit.js  404`
` Uncaught ReferenceError: $ is not defined`

Do i need to install something manually?
Thanks.

**Comment by idanb11** [comment]
might be related to: https://github.com/hoodiehq/hoodie-plugin-users/issues/37

**Comment by espy** [comment]
This seems to be the same issue as https://github.com/hoodiehq/hoodie-plugin-users/issues/37#issuecomment-73416721, let's continue the discussion over there for now. If it turns out to be different, we can re-open.
